### PR TITLE
Minimizing install-deps-*.sh execution time

### PR DESCRIPTION
**Pull request by LeeHayun**
This PR is part of #25. (+alpha)

## Major Changes
- Remove face detection API (temporary)
- install-deps-*.sh (#28)
  - Remove unused GStreamer packages
  - Utilize multi-core
  - Replace some build stages to package installation
    - libxml2, OpenCV, nodejs-4.x

## Minor Changes
- Add Apache LICENSE for Camera Framework
- Fix raspberry pi camera-config.json

## TODO
- I will implement face detection on the ML framework.

### CODE REVIEW

**Comment by LeeHayun** [comment]
@RedCarrottt
This version does not support face detection.

The haar classifier used for face detection is one of the machine learning techniques.
I removed face detection in the current version because I want face detection to be a feature of the ML framework.
When developing ML framework core is completed, I will add face detection API as ML API.

**Comment by RedCarrottt** [comment]
After you complete this PR, please merge commits with ```git rebase``` command.

**Comment by LeeHayun** [comment]
Finally, I tested on raspberry pi 3.
Below is the execution time of ```install-deps-raspberry-pi2_3.sh```.

time

Actually, each execution time is as follows.

step 1~2 |  step 3~11
-------- | ----------
about 10 mins | about 10 mins

In my environment, ```git clone``` is very slow.

**Comment by RedCarrottt** [comment]
How nice! :+1:

**Comment by jong1prk** [comment]
LGTM
Finally, annoying problem is solved.
Thanks!

**Pull request merged**
